# 02 — Read Iceberg Tables with Polars

Demonstrates reading the `demo.events` Iceberg table with PyIceberg + Polars.

Covers:
- Full table scan
- Predicate pushdown (filter at Iceberg file-scan layer)
- Column projection
- Overwrite as atomic delete + insert

**Time travel** is NOT shown here — see `07_iceberg_branches_tags.ipynb` (table-level refs)
and `08_nessie_catalog_refs.ipynb` (catalog-level commits).

**Prerequisites:** Run `01_write_iceberg_polars.ipynb` first.

In [1]:
import polars as pl
from pyiceberg.expressions import EqualTo
from pyiceberg.io.pyarrow import schema_to_pyarrow

import os

from pyiceberg.catalog.rest import RestCatalog

NESSIE_URI       = os.environ["NESSIE_URI"]
S3_ENDPOINT      = os.environ["AWS_S3_ENDPOINT"]
S3_ACCESS_KEY    = os.environ["AWS_ACCESS_KEY_ID"]
S3_SECRET_KEY    = os.environ["AWS_SECRET_ACCESS_KEY"]
WAREHOUSE_BUCKET = os.environ["ICEBERG_WAREHOUSE_BUCKET"]
WAREHOUSE_URI    = f"s3://{WAREHOUSE_BUCKET}/warehouse"

catalog = RestCatalog(
    name="nessie",
    **{
        "uri": NESSIE_URI,
        "warehouse": WAREHOUSE_URI,
        "s3.endpoint": S3_ENDPOINT,
        "s3.access-key-id": S3_ACCESS_KEY,
        "s3.secret-access-key": S3_SECRET_KEY,
        "s3.path-style-access": "true",
        "s3.region": "us-east-1",
    },
)

print("Connected to catalog:", catalog.name)

table = catalog.load_table(("demo", "events"))
table.refresh()
print("Table:", table.name())
print("Schema:")
print(table.schema())

Connected to catalog: nessie
Table: ('demo', 'events')
Schema:
table {
  1: event_id: required string
  2: user_id: optional long
  3: event_type: optional string
  4: amount: optional double
  5: ts: required timestamptz
}

## 1. Table metadata

In [2]:
history = table.history()
print(f"Snapshots in current metadata ({len(history)}):")
for snap in history:
    print(f"  id={snap.snapshot_id}  ts={snap.timestamp_ms}")

Snapshots in current metadata (1):
  id=7353798878884543153  ts=1778843183011

## 2. Full table scan → Polars DataFrame

In [3]:
df = pl.from_arrow(table.scan().to_arrow())

print(f"Shape: {df.shape}")
df

Shape: (7, 5)

shape: (7, 5)
┌──────────┬─────────┬────────────┬────────┬─────────────────────────┐
│ event_id ┆ user_id ┆ event_type ┆ amount ┆ ts                      │
│ ---      ┆ ---     ┆ ---        ┆ ---    ┆ ---                     │
│ str      ┆ i64     ┆ str        ┆ f64    ┆ datetime[μs, UTC]       │
╞══════════╪═════════╪════════════╪════════╪═════════════════════════╡
│ e006     ┆ 105     ┆ click      ┆ 0.0    ┆ 2024-01-18 09:00:00 UTC │
│ e007     ┆ 101     ┆ purchase   ┆ 99.0   ┆ 2024-01-18 10:30:00 UTC │
│ e001     ┆ 101     ┆ click      ┆ 0.0    ┆ 2024-01-15 10:00:00 UTC │
│ e002     ┆ 102     ┆ view       ┆ 0.0    ┆ 2024-01-15 11:00:00 UTC │
│ e003     ┆ 103     ┆ click      ┆ 0.0    ┆ 2024-01-16 09:00:00 UTC │
│ e004     ┆ 101     ┆ purchase   ┆ 49.99  ┆ 2024-01-16 14:00:00 UTC │
│ e005     ┆ 104     ┆ view       ┆ 0.0    ┆ 2024-01-17 08:00:00 UTC │
└──────────┴─────────┴────────────┴────────┴─────────────────────────┘

## 3. Predicate pushdown + column projection

The filter is evaluated at the Iceberg file-scan layer. Combined with the
`days(ts)` partition spec from notebook 01, time-bounded queries can prune
whole partitions without reading their Parquet files.

In [4]:
df_clicks = pl.from_arrow(
    table.scan(
        row_filter=EqualTo("event_type", "click"),
        selected_fields=("event_id", "user_id", "ts"),
    ).to_arrow()
)

print(f"Click events: {len(df_clicks)}")
df_clicks

Click events: 3

shape: (3, 3)
┌──────────┬─────────┬─────────────────────────┐
│ event_id ┆ user_id ┆ ts                      │
│ ---      ┆ ---     ┆ ---                     │
│ str      ┆ i64     ┆ datetime[μs, UTC]       │
╞══════════╪═════════╪═════════════════════════╡
│ e006     ┆ 105     ┆ 2024-01-18 09:00:00 UTC │
│ e001     ┆ 101     ┆ 2024-01-15 10:00:00 UTC │
│ e003     ┆ 103     ┆ 2024-01-16 09:00:00 UTC │
└──────────┴─────────┴─────────────────────────┘

## 4. Overwrite pattern (row-level update)

PyIceberg has no in-place row mutation. The standard pattern is
`overwrite()` with a filter — atomic delete-matching + insert.

For upsert/delete patterns, see [05_row_mutations.ipynb](05_row_mutations.ipynb).

In [5]:
import datetime

UTC = datetime.timezone.utc

updated_row = pl.DataFrame(
    {
        "event_id":   ["e002"],
        "user_id":    [102],
        "event_type": ["view"],
        "amount":     [5.99],
        "ts":         [datetime.datetime(2024, 1, 15, 11, 0, 0, tzinfo=UTC)],
    }
)

table.overwrite(
    updated_row.to_arrow().cast(schema_to_pyarrow(table.schema())),
    overwrite_filter=EqualTo("event_id", "e002"),
)
table.refresh()

print("✔ Overwrite complete. Snapshots:", len(table.history()))

df_after = pl.from_arrow(table.scan(row_filter=EqualTo("event_id", "e002")).to_arrow())
print("Updated row:")
df_after

✔ Overwrite complete. Snapshots: 1
Updated row:

shape: (1, 5)
┌──────────┬─────────┬────────────┬────────┬─────────────────────────┐
│ event_id ┆ user_id ┆ event_type ┆ amount ┆ ts                      │
│ ---      ┆ ---     ┆ ---        ┆ ---    ┆ ---                     │
│ str      ┆ i64     ┆ str        ┆ f64    ┆ datetime[μs, UTC]       │
╞══════════╪═════════╪════════════╪════════╪═════════════════════════╡
│ e002     ┆ 102     ┆ view       ┆ 5.99   ┆ 2024-01-15 11:00:00 UTC │
└──────────┴─────────┴────────────┴────────┴─────────────────────────┘

---
**Next:** [03_schema_evolution.ipynb](03_schema_evolution.ipynb) — add/drop/rename columns.